project/main/forms.py
# project/main/forms.py


from flask_wtf import Form
from wtforms import TextField
from wtforms.validators import DataRequired, Email, length


class SignUpForm(Form):
    email = TextField(
        'Enter your email address',
        validators=[DataRequired(), Email(), length(min=3)])

project/main/views.py
# project/main/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, request, flash, redirect, url_for

from forms import SignUpForm
from project import db
from project.models import Email


################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)


################
#### routes ####
################


@main_blueprint.route('/', methods=['GET', 'POST'])
def index():
    """Landing page for users to enter emails."""
    form = SignUpForm(request.form)
    if form.validate_on_submit():
        test = Email.query.filter_by(email=form.email.data).first()
        if test:
            flash('Sorry that email aleady exists!', 'danger')
        else:
            email = Email(email=form.email.data)
            db.session.add(email)
            db.session.commit()
            flash('Thank you for your interest!', 'success')
            return redirect(url_for('main.index'))
    return render_template('main/index.html', form=form)

project/user/views.py
# project/user/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required

from project import bcrypt
from project.models import User, Email
from project.user.forms import LoginForm

from project.calculators import RetirementCalc


################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)


################
#### routes ####
################

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """Login page for admins."""
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('user.admin'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.index'))


@user_blueprint.route('/admin')
@login_required
def admin():
    """Displays submitted emails to the admin."""
    signups = Email.query.all()
    return render_template('user/admin.html', signups=signups)

@user_blueprint.route('/admin/RetirementCalc')
@login_required
def retirementCalc():
    """Displays Retirement Calculation graphs for a specific user"""
    userinfo = Email.query.get(1)
    # print userinfo.__dict__
    info = {"currentValue":userinfo.currentValue,
            "companyMatch":userinfo.companyMatch,
            "yearlyContributions":userinfo.yearlyContributions,
            "age_at_retire":userinfo.age_at_retire,
            "dob":userinfo.dob}
    
    fv1 = RetirementCalc(info, 0.07)
    print fv1
    return render_template('user/retirementCalc.html')
    

project/templates/_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Flask-Landing{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link href="http://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/yeti/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{url_for('static', filename='css/main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>
  <body>

    {% include "navigation.html" %}

    <div class="container">

      <br>

      <!-- messages -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
           {{message}}
          </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
      {% endwith %}

      <!-- child template -->
      {% block content %}{% endblock %}

      <br>

      <!-- errors -->
      {% if error %}
        <p class="error"><strong>Error:</strong> {{ error }}</p>
      {% endif %}

      <br>
      <hr>

      {% block footer %}
      <footer class="footer">
        <p>Copyright &copy; 2017 <a href="http://www.AdviseYourself.com">AdvizeYourself</a>.</p>
      </footer>
      {% endblock %}

    </div>

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

project/templates/main/index.html
{% extends "_base.html" %}
{% block title %} - Welcome{% endblock %}

{% block content %}

<div id="main">

  <h1>Sign up today to stay updated.</h1>
    <br>
    <p>AdviseYourself.com is a website designed to take your financial planning into your own hands. We provide the tools you need to plan for your retirement, doublecheck your current investment portfolio, and keep tabs on your future.</p>
    <br>

  <form class="form-email" role="form" method="post" action="/">
    {{ form.csrf_token }}
    <p>
    {{ form.email.label }}
    <br>
    {{ form.email(placeholder="email@address.com") }}
    <span class="error">
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
    </p>
    <button class="btn btn-success btn-sm" type="submit">Submit!</button>
  </form>

</div>

{% endblock %}

project/templates/navigation.html
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Flask-Landing</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('user.admin') }}">Admin Page</a></li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
        {% else %}
          <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;Login</a></li>
        {% endif %}
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>